campos_tabelas = {
    "TbCliente": {
        "dsNome": {"type": "text", "required": False},
        "nrCnpj": {"type": "text", "required": False},
        "nrIe": {"type": "text", "required": False},
        "nrInscMun": {"type": "text", "required": False},
        "dsLogradouro": {"type": "text", "required": False},
        "nrNumero": {"type": "text", "required": False},
        "dsComplemento": {"type": "text", "required": False},
        "dsBairro": {"type": "text", "required": False},
        "dsCep": {"type": "text", "required": False},
        "dsCidade": {"type": "text", "required": False},
        "dsUF": {"type": "text", "required": False},
        "dsObs": {"type": "text", "required": False},
        "cdStatus": {"type": "text", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
        "cdClientePai": {"type": "integer", "required": False},
    },
    "TbClienteChave": {
        "dsChave": {"type": "text", "required": True},
        "dtRegistro": {"type": "timestamp with time zone", "required": False},
        "nrLimite": {"type": "integer", "required": False},
        "cdCliente": {"type": "integer", "required": True},
    },
    "TbDestinatario": {
        "dsNome": {"type": "text", "required": False},
        "nrCnpj": {"type": "text", "required": False},
        "nrIe": {"type": "text", "required": False},
        "nrInscMun": {"type": "text", "required": False},
        "dsLogradouro": {"type": "text", "required": False},
        "nrNumero": {"type": "text", "required": False},
        "dsComplemento": {"type": "text", "required": False},
        "dsBairro": {"type": "text", "required": False},
        "dsCep": {"type": "text", "required": False},
        "dsCidade": {"type": "text", "required": False},
        "dsUF": {"type": "text", "required": False},
        "dsObs": {"type": "text", "required": False},
        "cdStatus": {"type": "text", "required": False},
        "dsLat": {"type": "character varying", "required": False},
        "dsLong": {"type": "character varying", "required": False},
        "nrRaio": {"type": "double precision", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
        "cdCliente": {"type": "integer", "required": False},
        "cdEndereco": {"type": "integer", "required": False},
    },
    "TbDispositivo": {
        "dsDispositivo": {"type": "text", "required": False},
        "dsModelo": {"type": "integer", "required": False},
        "dsDescricao": {"type": "text", "required": False},
        "dsObs": {"type": "text", "required": False},
        "dsLayout": {"type": "text", "required": False},
        "nrChip": {"type": "bigint", "required": False},
        "cdStatus": {"type": "text", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
        "cdDestinatario": {"type": "integer", "required": False},
        "cdProduto": {"type": "integer", "required": False},
        "cdCliente": {"type": "integer", "required": False},
    },
    "TbImagens": {
        "dsCaminho": {"type": "character varying", "required": True},
        "cdCodigo": {"type": "character varying", "required": True},
        "dtRegistro": {"type": "timestamp", "required": False},
        "cdProduto": {"type": "integer", "required": False},
        "nrImagem": {"type": "integer", "required": False},
    },
    "TbPosicao": {
        "dsLat": {"type": "text", "required": False},
        "dsLong": {"type": "text", "required": False},
        "nrBat": {"type": "double precision", "required": False},
        "nrSeq": {"type": "integer", "required": False},
        "cdDispositivo": {"type": "integer", "required": False},
        "dsEndereco": {"type": "text", "required": False},
        "dsNum": {"type": "character varying", "required": False},
        "dsCep": {"type": "character varying", "required": False},
        "dsBairro": {"type": "character varying", "required": False},
        "dsCidade": {"type": "character varying", "required": False},
        "dsUF": {"type": "character varying", "required": False},
        "dsPais": {"type": "character varying", "required": False},
        "blArea": {"type": "boolean", "required": False},
        "nrDistancia": {"type": "real", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
        "cdDestinatario": {"type": "integer", "required": False},
    },
    "TbSensorRegistro": {
        "cdDispositivo": {"type": "integer", "required": True},
        "cdSensor": {"type": "integer", "required": True},
        "cdPosicao": {"type": "integer", "required": True},
        "cdProdutoItem": {"type": "integer", "required": False},
        "nrValor": {"type": "numeric", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
    },
    "TbTipoSensor": {
        "dsNome": {"type": "text", "required": True},
        "dsDescricao": {"type": "text", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
        "dsUnidade": {"type": "text", "required": True},
    },
    "TbProduto": {
        "dsNome": {"type": "text", "required": False},
        "dsDescricao": {"type": "text", "required": False},
        "nrCodigo": {"type": "text", "required": False},
        "nrLarg": {"type": "double precision", "required": False},
        "nrComp": {"type": "double precision", "required": False},
        "nrAlt": {"type": "double precision", "required": False},
        "cdStatus": {"type": "text", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
        "cdCliente": {"type": "integer", "required": False},
    },
    "TbProdutoItem": {
        "dsNome": {"type": "character varying", "required": False},
        "dsDescricao": {"type": "character varying", "required": False},
        "nrCodigo": {"type": "character varying", "required": False},
        "nrLarg": {"type": "double precision", "required": False},
        "nrComp": {"type": "double precision", "required": False},
        "nrAlt": {"type": "double precision", "required": False},
        "nrPesoUnit": {"type": "double precision", "required": False},
        "nrUnidade": {"type": "character varying", "required": False},
        "nrEmpilhamento": {"type": "integer", "required": False},
        "nrLastro": {"type": "integer", "required": False},
        "nrQtdeTotalSensor": {"type": "integer", "required": False},
        "cdStatus": {"type": "text", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
    },
    "TbSensor": {
        "cdDispositivo": {"type": "integer", "required": True},
        "cdProdutoItem": {"type": "integer", "required": False},
        "cdUnidade": {"type": "string", "required": False},
        "nrUnidadeIni": {"type": "integer", "required": False},
        "nrUnidadeFim": {"type": "integer", "required": False},
        "dtRegistro": {"type": "timestamp", "required": False},
        "cdTipoSensor": {"type": "bigint", "required": True},
    },
}
